import './globals.css';
import { Inter } from 'next/font/google';
import Nav from './components/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mockup Store',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch(
    'https://mockup-store-default-rtdb.europe-west1.firebasedatabase.app/mockupsCart.json',
    { cache: 'no-store' }
  );

  // if (!res.ok) {
  //   // This will activate the closest `error.js` Error Boundary
  //   throw new Error('Failed to fetch data');
  // }

  const data: any = (await res.json()) || [];

  const products: any[] = Object.values(data);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav data={products} />
        <main>{children}</main>
      </body>
    </html>
  );
}
